In [14]:
import numpy as np
%matplotlib notebook

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [15]:
A = np.array([[2, 4, -7], [3, -3, 0], [1, 7, 5]])
B = np.array([[2,4], [3, -3], [1,7]])
C = np.array([[-1, 1], [1, -1]])
D = np.array([[2, 0], [-3, 6]])

#Printing
print("Matices")
print("Matrix A: \n",A)
print("Matrix B: \n",B)
print("Matrix C: \n",C)
print("Matrix D: \n",D)

Matices
Matrix A: 
 [[ 2  4 -7]
 [ 3 -3  0]
 [ 1  7  5]]
Matrix B: 
 [[ 2  4]
 [ 3 -3]
 [ 1  7]]
Matrix C: 
 [[-1  1]
 [ 1 -1]]
Matrix D: 
 [[ 2  0]
 [-3  6]]


1. Multiply $\bf{A}$ by 2.5 

In [16]:
A_25 = A * 2.5
print("Matrix A multiplied by 2.5: \n",A_25)

Matrix A multiplied by 2.5: 
 [[  5.   10.  -17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [17]:
CA = np.matmul(C, A)
print("Matrix CA: \n",CA)

#Error because the number of columns in the first matrix do not match the number of rows in the second matrix

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [18]:
CD = np.matmul(C, D)
DC = np.matmul(D, C)
print("Matrix CD: \n",CD)
print("Matrix DC: \n",DC)

Matrix CD: 
 [[-5  6]
 [ 5 -6]]
Matrix DC: 
 [[-2  2]
 [ 9 -9]]


4. Find the transpose of $\bf{B}$

In [19]:
B_Tran = B.transpose()
print("Matrix B_Tran: \n",B_Tran)

Matrix B_Tran: 
 [[ 2  3  1]
 [ 4 -3  7]]


5. Add $\bf{C} + \bf{D}$

In [20]:
C_D = C + D
print("Matrix C_D: \n",C_D)

Matrix C_D: 
 [[ 1  1]
 [-2  5]]


6. Compute the determinate of $\bf{C}$

In [21]:
detC = np.linalg.det(C)
print("Determinate of C: ",detC)

Determinate of C:  0.0


7. Compute the determinate of $\bf{A}$

In [22]:
detA = np.linalg.det(A)
print("Determinate of A: ",detA)

Determinate of A:  -257.9999999999998
